apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.password | b64enc | quote }}
  postgres-postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
